
title: Invoke-Obfuscation VAR+ Launcher
author: Jonathan Cheong, oscd.community
date: 2020/10/15
description: Detects Obfuscated use of Environment Variables to execute PowerShell
detection:
  SELECTION_1:
    EventID: 4697
  SELECTION_2:
    ServiceFileName|re: .*cmd.{0,5}(?:/c|/r)(?:\s|)"set\s[a-zA-Z]{3,6}.*(?:\{\d\}){1,}\\"\s+?\-f(?:.*\)){1,}.*"
  condition: (SELECTION_1 and SELECTION_2)
falsepositives:
- Unknown
id: dcf2db1f-f091-425b-a821-c05875b8925a
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/17
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 8ca7004b-e620-4ecb-870e-86129b5b8e75
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
ruletype: SIGMA
