
title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION
author: Timur Zinniatullin, oscd.community
date: 2020/10/13
description: Detects Obfuscated Powershell via VAR++ LAUNCHER
detection:
  SELECTION_1:
    ServiceFileName|re: (?i).*&&set.*(\{\d\}){2,}\\"\s+?\-f.*&&.*cmd.*/c
  SELECTION_2:
    EventID: 4697
  condition: (SELECTION_1 and SELECTION_2)
falsepositives:
- Unknown
id: 4c54ba8f-73d2-4d40-8890-d9cf1dca3d30
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/18
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 14bcba49-a428-42d9-b943-e2ce0f0f7ae6
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
