
title: Invoke-Obfuscation Obfuscated IEX Invocation
author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
date: 2019/11/08
description: Detects all variations of obfuscated powershell IEX invocation code generated
  by Invoke-Obfuscation framework from the code block linked in the references
detection:
  SELECTION_1:
    EventID: 4697
  SELECTION_2:
    ServiceFileName|re: \$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[
  SELECTION_3:
    ServiceFileName|re: \$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[
  SELECTION_4:
    ServiceFileName|re: \$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[
  SELECTION_5:
    ServiceFileName|re: \$env:ComSpec\[(\s*\d{1,3}\s*,){2}
  SELECTION_6:
    ServiceFileName|re: \\*mdr\*\W\s*\)\.Name
  SELECTION_7:
    ServiceFileName|re: \$VerbosePreference\.ToString\(
  SELECTION_8:
    ServiceFileName|re: \String\]\s*\$VerbosePreference
  condition: (SELECTION_1 and (SELECTION_2 or SELECTION_3 or SELECTION_4 or SELECTION_5
    or SELECTION_6 or SELECTION_7 or SELECTION_8))
falsepositives:
- Unknown
id: fd0f5778-d3cb-4c9a-9695-66759d04702a
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/16
references:
- https://github.com/danielbohannon/Invoke-Obfuscation/blob/master/Out-ObfuscatedStringCommand.ps1#L873-L888"
related:
- id: 51aa9387-1c53-4153-91cc-d73c59ae1ca9
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
