# Standard profile minus MITRE ATT&CK Tactics and Record ID.
minimal:
    Timestamp: "%Timestamp%"
    RuleTitle: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    RecordID: "%RecordID%"
    Details: "%Details%"

standard:
    Timestamp: "%Timestamp%"
    RuleTitle: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    RecordID: "%RecordID%"
    Details: "%Details%"
    ExtraFieldInfo: "%ExtraFieldInfo%"

# Standard profile plus MitreTags(MITRE techniques, software and groups), rule filename and EVTX filename.
verbose:
    Timestamp: "%Timestamp%"
    RuleTitle: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    MitreTactics: "%MitreTactics%"
    MitreTags: "%MitreTags%"
    OtherTags: "%OtherTags%"
    RecordID: "%RecordID%"
    Details: "%Details%"
    ExtraFieldInfo: "%ExtraFieldInfo%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"

# Verbose profile with all field information instead of the minimal fields defined in the Details field.
all-field-info:
    Timestamp: "%Timestamp%"
    RuleTitle: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    RecordID: "%RecordID%"
    AllFieldInfo: "%AllFieldInfo%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"

# Verbose profile with all field information and tags.
all-field-info-verbose:
    Timestamp: "%Timestamp%"
    RuleTitle: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    MitreTactics: "%MitreTactics%"
    MitreTags: "%MitreTags%"
    OtherTags: "%OtherTags%"
    RecordID: "%RecordID%"
    AllFieldInfo: "%AllFieldInfo%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"

# As much information as possible.
super-verbose:
    Timestamp: "%Timestamp%"
    RuleTitle: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    RuleAuthor: "%RuleAuthor%"
    RuleModifiedDate: "%RuleModifiedDate%"
    Status: "%Status%"
    RecordID: "%RecordID%"
    Details: "%Details%"
    ExtraFieldInfo: "%ExtraFieldInfo%"
    MitreTactics: "%MitreTactics%"
    MitreTags: "%MitreTags%"
    OtherTags: "%OtherTags%"
    Provider: "%Provider%"
    RuleCreationDate: "%RuleCreationDate%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"

# Output that is compatible to import the CSV into Timesketch.
timesketch-minimal:
    datetime: "%Timestamp%"
    timestamp_desc: "hayabusa"
    message: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    MitreTactics: "%MitreTactics%"
    MitreTags: "%MitreTags%"
    OtherTags: "%OtherTags%"
    RecordID: "%RecordID%"
    Details: "%Details%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"

# Output that is compatible to import the CSV into Timesketch.
timesketch-verbose:
    datetime: "%Timestamp%"
    timestamp_desc: "hayabusa"
    message: "%RuleTitle%"
    Level: "%Level%"
    Computer: "%Computer%"
    Channel: "%Channel%"
    EventID: "%EventID%"
    MitreTactics: "%MitreTactics%"
    MitreTags: "%MitreTags%"
    OtherTags: "%OtherTags%"
    RecordID: "%RecordID%"
    Details: "%Details%"
    ExtraFieldInfo: "%ExtraFieldInfo%"
    RuleFile: "%RuleFile%"
    EvtxFile: "%EvtxFile%"