
title: Invoke-Obfuscation Via Use Clip
ruletype: Sigma
author: Nikita Nazarov, oscd.community
date: 2020/10/09
description: Detects Obfuscated Powershell via use Clip.exe in Scripts
detection:
  SELECTION_1:
    EventID: 4697
  SELECTION_2:
    ServiceFileName|re: (?i).*?echo.*clip.*&&.*(Clipboard|i`?n`?v`?o`?k`?e`?).*
  condition: (SELECTION_1 and SELECTION_2)
falsepositives:
- Unknown
id: 1a0a2ff1-611b-4dac-8216-8a7b47c618a6
level: high
logsource:
  product: windows
  service: security
modified: 2021/09/18
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: 63e3365d-4824-42d8-8b82-e56810fefa0c
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
