
title: Office Applications Spawning Wmi Cli
author: Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule)
date: 2021/08/23
description: Initial execution of malicious document calls wmic to execute the file
  with regsvr32
detection:
  SELECTION_1:
    EventID: 1
  SELECTION_2:
    Image: \wbem\WMIC.exe
  SELECTION_3:
    CommandLine: '*wmic *'
  SELECTION_4:
    OriginalFileName: wmic.exe
  SELECTION_5:
    Description: WMI Commandline Utility
  SELECTION_6:
    ParentImage:
    - '*winword.exe'
    - '*excel.exe'
    - '*powerpnt.exe'
  condition: (SELECTION_1 and (SELECTION_2 or SELECTION_3 or SELECTION_4 or SELECTION_5)
    and SELECTION_6)
falsepositives:
- Unknown
id: 518643ba-7d9c-4fa5-9f37-baed36059f6a
level: high
logsource:
  category: process_creation
  product: windows
modified: 2021/11/10
references:
- https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
- https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/main/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
status: experimental
tags:
- attack.t1204.002
- attack.t1047
- attack.t1218.010
- attack.execution
- attack.defense_evasion
